server:
  port: 80

#【游客模式】被允许访问的url设置
qiyun:
  security:
    setting:
       permitall: /register1

spring:
  thymeleaf:
    cache: false

# druid
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
     hikari:
       minimum-idle: 5
       maximum-pool-size: 15
       connection-test-query: SELECT 1
       max-lifetime: 1800000
       connection-timeout: 30000
       pool-name: DatebookHikariCP
